FROM  jenkins/ssh-agent:jdk11
USER  root
RUN   apt-get update && apt-get install -y lsb-release \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common
RUN   curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
                  https://download.docker.com/linux/debian/gpg 
RUN   echo "deb [arch=$(dpkg --print-architecture) \
            signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
            https://download.docker.com/linux/debian \
            $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN   apt-get update && apt-get install -y docker-ce docker-ce-cli
RUN   curl -fsSLO "https://nodejs.org/dist/v16.14.1/node-v16.14.1-linux-x64.tar.xz" && \
      tar -xJf "node-v16.14.1-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner     && \
      rm "node-v16.14.1-linux-x64.tar.xz" && \
      ln -s /usr/local/bin/node /usr/local/bin/nodejs
RUN   node --version && \ 
      npm --version && \ 
      docker --version
RUN   usermod -a -G docker jenkins && \
      groupmod -g 980 docker
