version: "3.9"
services:

    NodeApp1:
      container_name: nodeapp1
      image: nodeapp:latest
      restart: unless-stopped
      expose:
      - "8091"
      networks:
      - nodeapp

    NodeApp2:
      container_name: nodeapp2
      image: nodeapp:latest
      restart: unless-stopped
      expose:
      - "8092"
      networks:
      - nodeapp

    NodeApp3:
      container_name: nodeapp3
      image: nodeapp:latest
      restart: unless-stopped
      expose:
      - "8093"
      networks:
      - nodeapp

    Nginx:
      depends_on:
        - NodeApp1
        - NodeApp2
        - NodeApp3
      container_name: nginx
      image: nginxlb:latest
      ports:
      - "82:82"
      restart: unless-stopped
      networks:
      - nodeapp

networks:
  nodeapp:
