apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactapp-ingress
  namespace: jenkins
  labels:
    name: reactapp
spec:
  rules:
  - host: reactapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: reactapp-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  namespace: jenkins
  labels:
    app: reactapp
spec:
  selector:
    app: reactapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deploy
  namespace: jenkins
  labels:
    app: reactapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: victoribatraineedevops/training-repo:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
